# Generated by Django 3.0 on 2019-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSevenFifty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('software', models.FileField(upload_to='executable/')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareTwoFifty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('software', models.FileField(upload_to='executable/')),
            ],
        ),
        migrations.RenameModel(
            old_name='SoftwareUpload',
            new_name='SoftwareFiveHundred',
        ),
    ]
