# Generated by Django 3.0 on 2019-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsites', '0002_auto_20191221_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=250)),
            ],
        ),
    ]
