# Generated by Django 3.0 on 2020-01-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billsites', '0003_addressupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWebSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=250, verbose_name='Bitcoin Wallet')),
                ('country', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=30, verbose_name='Licence Key')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
