# Generated by Django 3.0 on 2020-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsites', '0004_mobilewebsoftware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilewebsoftware',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
